# Generated by Django 4.2.30 on 2026-05-17 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('stack', models.CharField(help_text='Ex: Django, React, PostgreSQL', max_length=300)),
                ('lien_github', models.URLField(blank=True)),
                ('lien_demo', models.URLField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('en_vedette', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(default='⚡', help_text='Emoji ou icone', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(default='Constanta Zinsou', max_length=100)),
                ('titre', models.CharField(default='Développeur Web Fullstack', max_length=150)),
                ('phrase_accroche', models.TextField(default='Je construis des applications web performantes et élégantes.')),
                ('bio', models.TextField(default='Passionné par le développement web, je crée des solutions digitales sur mesure depuis le Bénin.')),
                ('localisation', models.CharField(default='Cotonou, Bénin 🇧🇯', max_length=100)),
                ('langues', models.CharField(default='Français, Anglais', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='zinsouconstanta@gmail.com', max_length=254)),
                ('github', models.URLField(blank=True, default='https://github.com')),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com')),
                ('twitter', models.URLField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('annees_experience', models.PositiveIntegerField(default=3)),
                ('projets_realises', models.PositiveIntegerField(default=20)),
                ('clients_satisfaits', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pourcentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('categorie', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de données'), ('devops', 'DevOps & Outils')], default='backend', max_length=20)),
                ('icone', models.CharField(blank=True, help_text='Classe CSS ou emoji', max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('texte', models.TextField()),
                ('note', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('visible', models.BooleanField(default=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
