# Generated by Django 5.2.14 on 2026-05-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(default='innocentatcha32@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='nom_complet',
            field=models.CharField(default='Innocent ATCHA', max_length=100),
        ),
    ]
